// Generated by CoffeeScript 1.6.3
(function() {
  var WebServer, http, instance;

  http = require("http");

  WebServer = (function() {
    function WebServer(port) {
      this.port = port;
    }

    WebServer.prototype.dispatch = function(request, response) {
      response.writeHead(200, {
        "Content-Type": "text/plain"
      });
      response.write("Hello World");
      return response.end();
    };

    WebServer.prototype.run = function() {
      return http.createServer(this.dispatch).listen(this.port);
    };

    return WebServer;

  })();

  instance = new WebServer(8001);

  instance.run();

}).call(this);
