// Generated by CoffeeScript 1.6.3
(function() {
  var http, server;

  http = require("http");

  server = function(request, response) {
    response.writeHead(200, {
      "Content-Type": "text/plain"
    });
    response.write("Hello World");
    return response.end();
  };

  http.createServer(server).listen(8001);

}).call(this);
